### ISSUE TITLE
Publishing a NopCommerce 4.3 Release in Azure DevOps generates lots of extraneous files

### ISSUE THREAD

**Issue by Joebeazelman** [nopSolutions/nopCommerce#5502]
I am using Azure DevOps pipeline to build and deploy my site to my server. Even though **Release** is explicitly specified as a configuration in all the build tasks, the deployed IIS web folder is littered with Framework DLLs even though it is build for the shared framework runtime. There are also PDB dlls indicative or a **Debug** rather than a **Release** compilation. Since I can't build on my local machine due to a longstanding bug with **CopyPluginAssemblies**, I can't wether it happens locally on my development machine. It appears NopCommerce build settings is adhering to the build configuration settings.

There's also extraneous localization folders and it's unclear how to specify which languages you want your site to support.

Steps to reproduce the problem: 

```
variables:
  buildConfiguration: 'Release'
  dotnetSdkVersion: '3.1.301'
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'

stages:
... 
    - task: DotNetCoreCLI@2
      displayName: 'Build the project - $(buildConfiguration)'
      inputs:
        command: 'build'
        arguments: '--no-restore --configuration $(buildConfiguration)'
        projects: '**/*.csproj'
        
    - task: CopyFiles@2
      inputs:
        SourceFolder: src/Presentation/Nop.Web/App_Data
        Contents: 'dataSettings.json' 
        TargetFolder: '$(Build.ArtifactStagingDirectory)/$(buildConfiguration)/Nop.Web/App_Data'
        flattenFolders: true

    - task: DotNetCoreCLI@2
      displayName: 'Publish the project - $(buildConfiguration)'
      inputs:
        command: 'publish'
        projects: '$(System.DefaultWorkingDirectory)/**/Nop.Web.csproj' 
        publishWebProjects: false
        arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
        zipAfterPublish: true
```
