### ISSUE TITLE
Install fail : An exception was thrown while activating λ:FluentMigrator.Runner.IVersionLoader

### ISSUE THREAD

**Issue by LaplancheMaxime** [nopSolutions/nopCommerce#6379]
nopCommerce version: 4.50

Steps to reproduce the problem: 
- Use docker to up this stack : 
```
---
version: "3.4"
services:
    nopcommerce_web:
        image: nopcommerceteam/nopcommerce:4.50
        restart: "always"
        labels:
            - "traefik.enable=true"
        networks:
            - nop_db
            - server_stack_traefik
        depends_on:
            - nopcommerce_database

    nopcommerce_database:
        image: "postgres:14"
        restart: "always"
        environment:
            POSTGRES_PASSWORD: ROOTPASSWORD
            POSTGRES_DB: nop_db_db
            POSTGRES_USER: postgresroot
        networks:
            - nop_db

networks:
    nop_db:
    server_stack_traefik:
        external: true

```

When I launch the installation, i get this error : 
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/43656574/194947795-f02d209b-1f0f-4a84-8018-b2b95f6e7275.png">

Do you have a solution? Thank you
