### ISSUE TITLE
Custom theme not working in deploying through docker

### ISSUE THREAD

**Issue by amiry-jd** [nopSolutions/nopCommerce#7364]
nopCommerce version:  4.70.0

Steps to reproduce the problem: 

1- Copy DefaultClean theme and name it SomeTheme

2- Deploy using Docker and Docker-Compose (The files are below)

3- Go to admin panel. You won't see the new SomeTheme

4- Go inside the container by running `docker exec -it your_nop_instance sh` 

5- Run `ls -la /app/Themes` and you see there only is the `DefaultClean` theme and not your new theme. 

(I have same issue with my custom plugin - [here](https://stackoverflow.com/q/79067897/645167) and [here](https://www.nopcommerce.com/en/boards/topic/101014/custom-plugins-or-themes-not-working-in-deploying-through-docker) -, but lets focus on theme for now).

Dockerfile:

```bash
# create the build instance
FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build

WORKDIR /src
COPY ./src ./

WORKDIR /src/Presentation/Nop.Web

# build project
RUN dotnet build Nop.Web.csproj -c Release

# build plugins
WORKDIR /src/Plugins
RUN set -eux; \
    for dir in *; do \
    if [ -d "$dir" ]; then \
    dotnet build "$dir/$dir.csproj" -c Release; \
    fi; \
    done

# publish project
WORKDIR /src/Presentation/Nop.Web
RUN dotnet publish Nop.Web.csproj -c Release -o /app/published

WORKDIR /app/published

RUN mkdir logs bin

RUN chmod 775 App_Data \
    App_Data/DataProtectionKeys \
    bin \
    logs \
    Plugins \
    wwwroot/bundles \
    wwwroot/db_backups \
    wwwroot/files/exportimport \
    wwwroot/icons \
    wwwroot/images \
    wwwroot/images/thumbs \
    wwwroot/images/uploaded \
    wwwroot/sitemaps

# create the runtime instance
FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS runtime

# add globalization support
RUN apk add --no-cache icu-libs icu-data-full
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false

# installs required packages
RUN apk add tiff --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/main/ --allow-untrusted
RUN apk add libgdiplus --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/community/ --allow-untrusted
RUN apk add libc-dev tzdata --no-cache

# copy entrypoint script
COPY ./entrypoint.sh /entrypoint.sh
RUN chmod 755 /entrypoint.sh

WORKDIR /app

COPY --from=build /app/published .

ENV ASPNETCORE_URLS=http://+:80
EXPOSE 80

ENTRYPOINT "/entrypoint.sh"
```

docker-compose file:

```yaml
services:
    my_nop:
        container_name: my_nop
        hostname: my_nop
        image: jd/my_nop
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - my_nop:/app
        env_file:
            - ./.env
        ports:
            - "${WEB_EXPOSE_PORT}:80"
        networks:
            default:
            infra:
volumes:
    my_nop:
        name: my_nop
```
