### ISSUE TITLE
Docker compose api and db container race condition

### ISSUE THREAD

**Issue by amrali21** [nopSolutions/nopCommerce#7688]
When starting the app using docker compose , We could face the issue of the api starting before the db service. This would result an error in the api and the api then container will exit with code 139. Even though we have a 'depends_on' property in the api service, This guarantees the order of container startup, But doesn't guarantee the db service in the container started and is ready to accept connections.

To reproduce this error we could introduce extra 30 sec delay before starting the sql server service by overriding the startup command of the DB service like so

```
nopcommerce_database:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        container_name: nopcommerce_mssql_server
        environment:
            SA_PASSWORD: "nopCommerce_db_password"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"
        command: ["sh", "-c", "sleep 30 && /opt/mssql/bin/sqlservr"]
```

To fix this potential race condition we could add a health-check to the db service, or add periodic delay to the API container to wait till the SQL server service is up.
